General:
    comment: Test num-tile 64 tiel size 192, and test spiral tile
    seed: 1222
    fp16: True
    amp_level: O1
    multi_gpu_mode: ddp
    gpus: [0]
    epoch: &epoch 30
    grad_acc: 2
    debug: False  # This value overwritten in train.py

Data:
    dataset:
        train_df: ../input/train-5kfold.csv
        kfold: -1
        tile_option: normal
        random_tile_train: True
        random_rotate_tile: False
        random_tile_white: False
        img_size: 1536
        num_tile: 64
        tile_size: 192
        mask: False
        mask_ch: &mask_ch 4
        mode_aug: True
        spiral_tile: True
    dataloader:
        batch_size: 6
        num_workers: 5

Model:
    base: efficientnet-b1
    in_channel: 3
    out_channel: 10
    out_channel_seg: *mask_ch
    pretrained: True
    pool_type: gem

Optimizer:
    optimizer:
        name: Adam
        params:
            lr: !!python/float 3e-5
            amsgrad: False
    lr_scheduler:
        name: CosineAnnealingLR
        params:
            T_max: *epoch
            last_epoch: -1

Loss:
    train:
        base_loss:
            name: BCEWithLogitsLoss
            params:
                reduction: mean
    valid:
        base_loss:
            name: BCEWithLogitsLoss
            params:
                reduction: mean

Augmentation:
    train:
        - name: Transpose
          params:
              p: 0.5
        - name: HorizontalFlip
          params:
              p: 0.5
        - name: VerticalFlip
          params:
              p: 0.5
        - name: RandomRotate90
          params:
              p: 0.5
        - name: ShiftScaleRotate
          params:
              p: 0.5
              rotate_limit: 10
              shift_limit: 0.05
              scale_limit: 0.05
        - name: OneOf
          member:
              - name: ElasticTransform
                params:
                    alpha: 120
                    sigma: 6
                    alpha_affine: 3.6
              - name: GridDistortion
              - name: OpticalDistortion
                params:
                    distort_limit: 0.1
                    shift_limit: 0.1
          params:
              p: 0.5
    valid:
