General:
    comment: Sample config file
    seed: 1222
    fp16: True
    # Compile level for AMP, O1, O2, O1 is better
    amp_level: O1
    # ddp, ddp2, dp, none
    # FP16 not support dp
    multi_gpu_mode: ddp
    gpus: [0]
    epoch: &epoch 25
    # Gradient accumulation option
    grad_acc: 1
    debug: False  # This value overwritten in train.py

Data:
    dataset:
        train_df: ../input/train-10kfold.csv
        train_img_dir: ../input/train_images
        img_height: 1024
        img_width: 1024
        # kfold is overwritten in train.py
        kfold: -1
        random_tile_train: True
    dataloader:
        # If use_sampler is True, batch size of each loader is batch_size / (number of gpus)
        batch_size: 32
        num_workers: 4
        # These option is used for ddp
        train:
            use_sampler: True
            change_rate_sampler: False
            max_pos_rate: 1.0
        valid:
            use_sampler: True
        test:
            use_sampler: False

Model:
    base: resnet18
    # model_arch: normal, large_input
    model_arch: normal
    in_channel: 3
    out_channel: 1
    pretrained: True
    output: softmax

Optimizer:
    optimizer: Adam
    init_lr: !!python/float 1e-4
    lr_scheduler:
        name: CosineAnnealingLR
        params:
            T_max: *epoch
            eta_min: !!python/float 5e-6
            last_epoch: -1

Loss:
    base_loss:
#        name: MSELoss
#        name: BalancedL1Loss
#        params:
#            reduction: mean
        name: SmoothL1Loss
        params:
            reduction: mean

Augmentation:
    # tta: hflip, vflip
    tta: []
    train:
        - name: HorizontalFlip
          params:
              p: 0.5
        - name: VerticalFlip
          params:
              p: 0.5
        - name: RandomRotate90
          params:
              p: 0.5
        - name: ShiftScaleRotate
          params:
              p: 0.5
              rotate_limit: 10
              shift_limit: 0.05
              scale_limit: 0.05
        - name: OneOf
          member:
              - name: ElasticTransform
                params:
                    alpha: 120
                    sigma: 6
                    alpha_affine: 3.6
              - name: GridDistortion
              - name: OpticalDistortion
                params:
                    distort_limit: 0.1
                    shift_limit: 0.1
          params:
              p: 0.5
        - name: Normalize
          params:
              p: 1.0
              mean: [0.86821552, 0.73319595, 0.81884091]
              std: [0.37468367, 0.5095725, 0.4131941]
    valid:
        - name: Normalize
          params:
              p: 1.0
              mean: [0.86821552, 0.73319595, 0.81884091]
              std: [0.37468367, 0.5095725, 0.4131941]
